services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      image: freedium
      container_name: freedium 
      target: base
    ports:
      - "64110:8000"
    environment:
      - DEBUG=false
      - HOST=0.0.0.0
      - PORT=8000
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    env_file:
      - .env
    restart: always